name: Generate APK
on:
  push:
    branches: [ master ]

jobs:
  # A job to generate debug APK and upload on Github Artifacts
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v4.1.0
      - name: set up JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17

      - name: Build debug APK
        run: ./gradlew build

      - name: Upload APK to Github Artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: AppDebug.apk
          path: app/build/outputs/apk/debug/app-debug.apk