name: Generate APK
on:
  push:
    branches: [ master ]

jobs:
  # A job to generate debug APK and upload on Github Artifacts
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload APK to Github Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AppDebug.apk
          path: app/build/outputs/apk/debug/app-debug.apk