name: Master Release CI
on:
  push:
      branches:
        - 'release'

jobs:
  # A job to generate debug APK and upload on Github Artifacts
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload APK to Firebase App Distribuition
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
         appId: ${{ secrets.FIREBASE_APP_ID }}
         token: ${{ secrets.FIREBASE_TOKEN }}
         groups: QAs
         file: app/build/outputs/apk/debug/app-debug.apk
